### ISSUE TITLE
Group project- Milestone 2

### ISSUE THREAD

**Issue by Bob-2020cs** [data301-2020-winter1/course-project-group_6001#4]
## High priority (must-fix)

- [ ]  Explore relationships between variables using Scatterplot

- [x] Add description in all the graphs, especially define your motive and outcome. Make sure you pass your message to the reader.  (especially in python notebooks)

- [x] Your research question should be "How do education and work hours affect the annual salary?"

- [x] Explore how per hour income is related to education.

## Medium Priority (should-fix)
- [x] Try different data cleaning methods (e.g., searching for duplicates, remove outliers, remove missing values)

- [x] Rename the folders inside the Analysis folder (e.g., filename1, filename2)

- [x] Make the Pie charts readable in 
course-project-group_6001/analysis/Analysis of the Adult income dataset-2.md

## Low priority (fix if there is time)
- [ ] Find out which attribute or a set of attributes increases the annual salary at first, then jump to the research question.

- [ ] Add graph labels on both the axis.

**Comment by bChakrabarty** [comment]
Some graphs still missing detail especially the motive.
course-project-group_6001/analysis/Bob/Milestone2-EDA.ipynb
